### ISSUE TITLE
Use normal screws

### ISSUE THREAD

**Issue by singpolyma** [MycroftAI/hardware-mycroft-mark-1#1]
For future designs, consider using screws that users are likely to have a screwdriver for.

**Comment by davbl** [comment]
The team went back and forth on this. We eventually decided on Torx due to its advantages over the Phillips screws, some of which are mentioned [here](https://en.wikipedia.org/wiki/Torx#Principles_of_operation). As for the tool availability, I am told we include a Torx wrench in Mark I boxes. If you didn't get it in yours, send me a message, and I'll sort it out!

**Comment by singpolyma** [comment]
I certainly didn't receive a driver with mine. Ended up buying a torx set (two, actually, first one wasn't long enough) so I could repair my Mark I

AFAICT torx screws are basically low-grade physical DRM equivalent for hardware

**Comment by penrods** [comment]
The feedback is definitely appreciated.  As you noted, the depth/narrowness of the channel was also a challenge -- I own Torx drivers, but they were too wide to fit.  Torx do have some legit advantages -- I've never stripped out a Torx screw -- but they are not nearly as common.

As David mentioned, including a Torx driver is now done by default.  Once we realized this was an issue for many people we started including a "screwdriver" similar to what you get with Ikea furniture in the boxes.  We are happy to send one if you'd like, but for most of the early batches who have contacted us it is faster/easier to hit a local store rather than wait.

Sorry about the hassle, we are learning as we go on this!

**Comment by kalon33** [comment]
@singpolyma same thing here, I didn't received a Torx wrench in my Mark I box and had to buy one today as my Mycroft won't boot and I had to try a microSD image restoring...

**Comment by tiredoftry** [comment]
Looking for a driver for my screws as well.  It would be nice if the SD card was accessible without taking the Mark I apart.  Hopefully, this will be a feature on the Mark II.

**Comment by ruth-connect** [comment]
Do you know what size Torx screwdriver you need for opening the Mark I please? The smallest screwdriver I have currently is a T15 - and that is too big.
